ShopDongHo/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopDongHo.Models;
using ShopDongHo.Libs;
using System.Data.Entity;

namespace ShopDongHo.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
		private ShopDongHoEntities db = new ShopDongHoEntities();

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Unauthorized()
		{
			return View();
		}

		public ActionResult ChangePassword()
		{
			//ModelState.AddModelError("ErrorChangePassword", "");
			return View();

		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult ChangePassword([Bind(Include = "MatKhau,MatKhauMoi,XacNhanMatKhauMoi")] NhanVienChangePassword nhanVienChangePassword)
		{
			if (ModelState.IsValid)
			{
				int manv = Convert.ToInt32(Session["MaNhanVien"]);
				NhanVien nhanVien = db.NhanVien.Find(manv);
				if (nhanVien == null)
				{
					return HttpNotFound();
				}
				nhanVienChangePassword.MatKhau = SHA1.ComputeHash(nhanVienChangePassword.MatKhau);
				if (nhanVien.MatKhau == nhanVienChangePassword.MatKhau)
				{
					nhanVienChangePassword.MatKhauMoi = SHA1.ComputeHash(nhanVienChangePassword.MatKhauMoi);
					nhanVienChangePassword.XacNhanMatKhauMoi = nhanVienChangePassword.MatKhauMoi;

					nhanVien.MatKhau = nhanVienChangePassword.MatKhauMoi;
					nhanVien.XacNhanMatKhau = nhanVienChangePassword.MatKhauMoi;

					db.Entry(nhanVien).State = EntityState.Modified;
					db.SaveChanges();
					return RedirectToAction("Logout");
				}
				else
				{
					ViewBag.error = "Mật khẩu cũ không đúng !!!";
					return View();
				}

			}
			return View(nhanVienChangePassword);
		}

		public ActionResult Logout()
		{
			// Xóa SESSION
			Session.RemoveAll();

			// Quay về trang chủ
			return RedirectToAction("Index", "Home");
		}

		// GET: Home/Login
		public ActionResult Login()
		{
			ModelState.AddModelError("LoginError", "");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Login(NhanVienLogin nhanVien)
		{
			if (ModelState.IsValid)
			{
				string matKhauMaHoa = SHA1.ComputeHash(nhanVien.MatKhau);
				var taiKhoan = db.NhanVien.Where(r => r.TenDangNhap == nhanVien.TenDangNhap && r.MatKhau == matKhauMaHoa).SingleOrDefault();

				if (taiKhoan == null)
				{
					ModelState.AddModelError("LoginError", "Tên đăng nhập hoặc mật khẩu không chính xác!");
					return View(nhanVien);
				}
				else
				{
					// Đăng ký SESSION
					Session["MaNhanVien"] = taiKhoan.ID;
					Session["HoTenNhanVien"] = taiKhoan.HoVaTen;
					Session["Quyen"] = taiKhoan.Quyen;

					// Quay về trang chủ
					return RedirectToAction("Index", "Home");
				}
			}

			return View(nhanVien);
		}
	}
}

ShopDongHo/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopDongHo.Models;

namespace ShopDongHo.Controllers
{
    public class GioHangController: Controller
    {
        private ShopDongHoEntities db = new ShopDongHoEntities();
        // GET: GioHang
       
        public ActionResult Index()
        {        
            return View();
        }

        // GET: GioHang/ThemVaoGio/{maSP}
        public ActionResult ThemVaoGio(int maSP)
        {
            if (Session["cart"] == null)
            {
                var sp = db.DongHo.Find(maSP);
                List<SanPhamTrongGio> cart = new List<SanPhamTrongGio>();
                cart.Add(new SanPhamTrongGio { dongho = sp, soLuongTrongGio = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
                int index = isExist(maSP);
                if (index != -1)
                {
                    cart[index].soLuongTrongGio++;
                }
                else
                {
                    var sp = db.DongHo.Find(maSP);
                    cart.Add(new SanPhamTrongGio { dongho = sp, soLuongTrongGio = 1 });
                }
                Session["cart"] = cart;
            }

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatTang/{maSP}
        public ActionResult CapNhatTang(int maSP)
        {
            var sp = db.DongHo.Find(maSP);
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio <= 10)
                    if(item.soLuongTrongGio < sp.SoLuong)
                    {
                        item.soLuongTrongGio++;
                    }
                    else
                    {
                        TempData["Message"] = "Sản phẩm không đủ số lượng hiện có " + sp.SoLuong;
                    }
                    
            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatGiam/{maSP}
        public ActionResult CapNhatGiam(int maSP)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio >= 1)
                    item.soLuongTrongGio--;
            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/XoaKhoiGio/{maSP}
        public ActionResult XoaKhoiGio(int maSP)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            int index = isExist(maSP);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].dongho.ID.Equals(id))
                    return i;
            return -1;
        }
    }
}

ShopDongHo/Controllers/HomeController.cs
using Microsoft.Azure.Documents;
using ShopDongHo.Libs;
using ShopDongHo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ShopDongHo.Controllers
{
    public class HomeController : Controller
	{
		private ShopDongHoEntities db = new ShopDongHoEntities();

		// GET: Home
		public ActionResult Index()
		{
			var dongho = db.DongHo.Where(r => r.SoLuong > 0).ToList();
			return View(dongho);
		}

		public ActionResult _Catelogies()
		{
			var loai = db.ThuongHieu.OrderBy(r => r.TenThuongHieu).ToList();
			return PartialView(loai);
		}

		public ActionResult SubPosts(int id)
		{
			var baiviet = db.DongHo.Where(r => r.ThuongHieu_ID == id ).ToList();
			return View(baiviet);
		}

		[HttpPost]
		public ActionResult Search(FormCollection collection)
		{
			string tukhoa = collection["Tukhoa"].ToString();
			var baiViet = db.DongHo.Where(r=>r.TenDongHo.Contains(tukhoa) || r.MoTa.Contains(tukhoa)).ToList();
			return View(baiViet);
		}

		public ActionResult Details(int maSP)
		{
			var dongho = db.DongHo.Where(r => r.ID == maSP ).SingleOrDefault();
			return View(dongho);
		}

		public ActionResult BuyMost()
		{
			var bestSale = (from dh in db.DongHo
							join ct in db.DatHang_ChiTiet on dh.ID equals ct.DongHo_ID
							join dhang in db.DatHang on ct.DatHang_ID equals dhang.ID
							where (ct.SoLuong > 0)							
							select new BestSaleModels(){ 
								TenDongHo =dh.TenDongHo,
								HinhAnhDH=dh.HinhAnhDH,
								DonGia =dh.DonGia,
								ID=dh.ID,
								SoLuong=ct.SoLuong
							}).OrderByDescending(ct =>ct.SoLuong).Distinct().ToList();
			
			return View(bestSale);
		}

		public ActionResult MyOrders()
		{
			int makh = Convert.ToInt32(Session["MaKhachHang"]);
			var Myorders = (from dh in db.DongHo
							join ct in db.DatHang_ChiTiet on dh.ID equals ct.DongHo_ID
							join dhang in db.DatHang on ct.DatHang_ID equals dhang.ID 
							join kh in db.KhachHang on  dhang.KhachHang_ID equals kh.ID 
							where(kh.ID == makh)

							select new Myorders()
							{
								TenDongHo = dh.TenDongHo,
								HinhAnhDH = dh.HinhAnhDH,
								DonGia = ct.DonGia,
								ID = kh.ID,
								SoLuong = ct.SoLuong,
								NgayDatHang = dhang.NgayDatHang

							}).OrderByDescending(dhang => dhang.NgayDatHang).ToList();

			return View(Myorders);
		}

		public ActionResult ChangePassword()
		{
			//ModelState.AddModelError("ErrorChangePassword", "");
			return View();
			
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult ChangePassword([Bind(Include = "MatKhau,MatKhauMoi,XacNhanMatKhauMoi")] KhachHangChangePassword khachHangChangePassword )
		{	
			if (ModelState.IsValid)
			{
				int makh = Convert.ToInt32(Session["MaKhachHang"]);
				KhachHang khachHang = db.KhachHang.Find(makh);				
				if(khachHang == null)
                {
					return HttpNotFound();
                }
				khachHangChangePassword.MatKhau = SHA1.ComputeHash(khachHangChangePassword.MatKhau);
				if(khachHang.MatKhau == khachHangChangePassword.MatKhau)
                {
					khachHangChangePassword.MatKhauMoi = SHA1.ComputeHash(khachHangChangePassword.MatKhauMoi);
					khachHangChangePassword.XacNhanMatKhauMoi = khachHangChangePassword.MatKhauMoi;

					khachHang.MatKhau = khachHangChangePassword.MatKhauMoi;
					khachHang.XacNhanMatKhau = khachHangChangePassword.MatKhauMoi;

					db.Entry(khachHang).State = EntityState.Modified;
					db.SaveChanges();
					return RedirectToAction("Login");
				}
                else
                {
					ViewBag.error = "Mật khẩu cũ không đúng !!!";
					return View();
				}

				
			}
			return View(khachHangChangePassword);
		}

		public ActionResult success()
		{
			return View();
		}
		//GET: Register
		public ActionResult Register()
		{
			return View();
		}

		//POST: Register
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Register(KhachHang khachHang)
		{
			if (ModelState.IsValid)
			{
				var check = db.KhachHang.FirstOrDefault(r => r.TenDangNhap == khachHang.TenDangNhap);
				if (check == null)
				{
					khachHang.MatKhau = SHA1.ComputeHash(khachHang.MatKhau);
					khachHang.XacNhanMatKhau = SHA1.ComputeHash(khachHang.XacNhanMatKhau);

					db.Configuration.ValidateOnSaveEnabled = false;
					db.KhachHang.Add(khachHang);
					db.SaveChanges();
					return RedirectToAction("success");
				}
				else
				{
					ViewBag.error = "Tên đăng nhập đã tồn tại !!!";
					return View();
				}
			}
			return View();
		}

		// GET: Home/ThanhToan
		public ActionResult ThanhToan()
		{
			if (Session["MaKhachHang"] == null)
			{
				return RedirectToAction("Login", "Home");
			}
			else
			{
				return View();
			}
		}

		// POST: Home/ThanhToan
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult ThanhToan(DatHang datHang)
		{
			if (ModelState.IsValid)
			{
				// Lưu vào bảng DatHang
				DatHang dh = new DatHang();
				dh.DiaChiGiaoHang = datHang.DiaChiGiaoHang;
				dh.DienThoaiGiaoHang = datHang.DienThoaiGiaoHang;
				dh.NgayDatHang = DateTime.Now;
				dh.KhachHang_ID = Convert.ToInt32(Session["MaKhachHang"]);
				dh.TinhTrang = 0;
				db.DatHang.Add(dh);
				db.SaveChanges();

				// Lưu vào bảng DatHang_ChiTiet
				List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
				foreach (var item in cart)
				{
					DatHang_ChiTiet ct = new DatHang_ChiTiet();
					ct.DatHang_ID = dh.ID;
					ct.DongHo_ID = item.dongho.ID;
					ct.SoLuong = Convert.ToInt16(item.soLuongTrongGio);
					ct.DonGia = item.dongho.DonGia;
					db.DatHang_ChiTiet.Add(ct);
					var dongho = db.DongHo.Find(item.dongho.ID);
					dongho.SoLuong -= item.soLuongTrongGio;
					db.SaveChanges();
				}

				// Xóa giỏ hàng
				cart.Clear();

				// Quay về trang chủ
				return RedirectToAction("Index", "Home");
			}

			return View(datHang);
		}

		// GET: Home/Login
		public ActionResult Login()
		{
			ModelState.AddModelError("LoginError", "");
			return View();
		}

		// POST: Home/Login
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Login(KhachHangLogin khachHang)
		{
			if (ModelState.IsValid)
			{
				string matKhauMaHoa = SHA1.ComputeHash(khachHang.MatKhau);
				var taiKhoan = db.KhachHang.Where(r => r.TenDangNhap == khachHang.TenDangNhap && r.MatKhau == matKhauMaHoa).SingleOrDefault();

				if (taiKhoan == null)
				{
					ModelState.AddModelError("LoginError", "Tên đăng nhập hoặc mật khẩu không chính xác!");
					return View(khachHang);
				}
				else
				{
					// Đăng ký SESSION
					Session["MaKhachHang"] = taiKhoan.ID;
					Session["HoTenKhachHang"] = taiKhoan.HoVaten;

					// Quay về trang chủ
					return RedirectToAction("Index", "Home");
				}
			}

			return View(khachHang);
		}
		public ActionResult Logout()
		{
			// Xóa SESSION
			Session.RemoveAll();

			// Quay về trang chủ
			return RedirectToAction("Index", "Home");
		}
	}
}

ShopDongHo/Views/Home/BuyMost.cshtml
@model IEnumerable<ShopDongHo.Models.BestSaleModels>

@{
    ViewBag.Title = "Đồng hồ được mua nhiều nhất tại Watch Luxury Store";
}
<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        <div class="card-deck">
            @{ int stt = 1; }
            @foreach (var item in Model)
            {

                <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-12">
                    <div class="card list-books">
                        <span class="alert text-danger"  >Bán chạy @stt</span>
                        <img src="~/@item.HinhAnhDH" class="card-img-top" alt="...">

                        <div class="card-body al">
                            <h5 class="card-title text-center">@item.TenDongHo</h5>
                            <p class="card-text text-center">@String.Format("{0:N0}", item.DonGia) VNĐ</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="@Url.Action("Details", "Home", new { maSP = item.ID })" class="btn btn-info m-1">Chi tiết</a>
                        </div>
                    </div>
                </div>
                stt++;
            }
        </div>
    </div>
</div>

ShopDongHo/Views/Home/ChangePassword.cshtml
@model ShopDongHo.Models.KhachHangChangePassword
@{
    ViewBag.Title = "Đổi mật khẩu khách hàng";
}

<div class="card mt-3 w-50 m-auto">
    <h5 class=" card-header info-color white-text text-center py-4 ">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
           
            <div class="form-group">
                @Html.LabelFor(model => model.MatKhau)
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                @if (ViewBag.error != null)
                {
                    <span class="badge badge-danger mt-2">@ViewBag.error</span>
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatKhauMoi)
                @Html.EditorFor(model => model.MatKhauMoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhauMoi, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.XacNhanMatKhauMoi)
                @Html.EditorFor(model => model.XacNhanMatKhauMoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XacNhanMatKhauMoi, "", new { @class = "text-danger" })
            </div>


            <div class="form-group mb-0">
                <input type="submit" value="Xác nhận " class="btn btn-success" /> hoặc @Html.ActionLink("Quay về trang chủ", "Index", "Home")
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShopDongHo/Views/Home/Details.cshtml
@model ShopDongHo.Models.DongHo
@{
    ViewBag.Title = Model.TenDongHo;
}
<div class="card mt-2">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        <p>@Html.Raw(Model.MoTa)</p> <!--chuyền nội dung mã hóa-->
    </div>
</div>

ShopDongHo/Views/Home/Index.cshtml
@model IEnumerable<ShopDongHo.Models.DongHo>
@{
    ViewBag.Title = "Watch Luxury Store";
}
<div>
    <div id="slider" class="carousel slide" data-ride="carousel">


        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Images/slide1.jpg" class="d-block w-100" alt="">
            </div>
            <div class="carousel-item">
                <img src="~/Images/slide2.jpg" class="d-block w-100" alt="">
            </div>
            <div class="carousel-item">
                <img src="~/Images/slide3.jpg" class="d-block w-100" alt="">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#slider" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#slider" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>

    </div>

    <div class="card mt-3">
        <h5 class="card-header">@ViewBag.Title</h5>
        <div class="card-body">
            <div class="card-deck">
                @foreach (var item in Model)
                {
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-12">
                        <div class="card list-books">
                            <img src="~/@item.HinhAnhDH" class="card-img-top" alt="...">
                            <div class="card-body al">
                                <h5 class="card-title text-center">@item.TenDongHo</h5>
                                <p class="card-text text-center">@String.Format("{0:N0}", item.DonGia) VNĐ</p>
                            </div>
                            <div class="card-footer text-center">
                                <a href="@Url.Action("Details", "Home", new { maSP = item.ID })" class="btn btn-info m-1 fas fa-info-circle"> Chi tiết</a>
                            </div>
                        </div>
                    </div>        
                }
            </div>
        </div>
    </div>
</div>

ShopDongHo/Views/Home/MyOrders.cshtml
@model IEnumerable<ShopDongHo.Models.Myorders>

@{
    ViewBag.Title = "Đơn hàng của tôi";
}

<link href="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js" rel="stylesheet" />

<div class="card mt-3">
    <h5 class="card-header">Đơn hàng của  @Session["HoTenKhachHang"].ToString()</h5>
    <div class="card-body">
        <table id="Panigation" class="table table-bordered table-hover table-sm mb-0">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th>Hình ảnh</th>
                    <th>Sản phẩm</th>
                    <th width="10%">Số lượng</th>
                    <th>Đơn giá</th>
                    <th>Thành tiền</th>
                    <th>Thời gian đặt hàng</th>
                </tr>
            </thead>
            <tbody>
                @{ int stt = 1; }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@stt</td>
                        <td><img src="~/@item.HinhAnhDH" width="150" /></td>
                        <td>@item.TenDongHo</td>
                        <td>@item.SoLuong</td>
                        <td class="text-right">@String.Format("{0:N0}", item.DonGia) VNĐ</td>
                        <td class="text-right">@String.Format("{0:N0}", item.DonGia * item.SoLuong) VNĐ</td>
                        <td>@item.NgayDatHang</td>
                    </tr>
                    stt++;
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            $('#Panigation').DataTable({
                "language": {
                    "lengthMenu": "Số dòng _MENU_  trên trang ",
                    "zeroRecords": "Không tìm thấy!!!",
                    "info": "Trang  _PAGE_ của _PAGES_",
                    "infoEmpty": "Không có sẵn dữ liệu",
                    "infoFiltered": "(được lọc từ tổng _MAX_  dữ liệu)"
                }
            });
        });
    </script>
}

ShopDongHo/Views/Home/ThanhToan.cshtml
@model ShopDongHo.Models.DatHang

@{
    ViewBag.Title = "Thanh toán";
}

<div class="card mt-3">
    <h5 class="card-header">Thông tin thanh toán</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.DienThoaiGiaoHang)
                @Html.EditorFor(model => model.DienThoaiGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiGiaoHang, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChiGiaoHang)
                @Html.EditorFor(model => model.DiaChiGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiGiaoHang, "", new { @class = "text-danger" })
            </div>

            <div class="form-group mb-0">
                <input type="submit" value="Thanh toán" class="btn btn-success" /> hoặc @Html.ActionLink("Quay về trang chủ", "Index", "Home")
            </div>
        }
    </div>
</div>

<div class="card mt-3">
    <h5 class="card-header">Thông tin sản phẩm đặt mua</h5>
    <div class="card-body">
        <table class="table table-bordered table-hover table-sm">
            <tr>
                <th width="5%">#</th>
                <th>Hình ảnh</th>
                <th>Sản phẩm</th>
                <th width="10%">Số lượng</th>
                <th>Đơn giá</th>
                <th>Thành tiền</th>
            </tr>
            @foreach (var item in (List<ShopDongHo.Models.SanPhamTrongGio>)Session["cart"])
            {
                <tr>
                    <td>#</td>
                    <td><img src="~/@item.dongho.HinhAnhDH" width="50" /></td>
                    <td>@item.dongho.TenDongHo</td>
                    <td>@item.soLuongTrongGio</td>
                    <td class="text-right">@String.Format("{0:N0}", item.dongho.DonGia) VNĐ</td>
                    <td class="text-right">@String.Format("{0:N0}",(item.soLuongTrongGio * item.dongho.DonGia))  VNĐ</td>
                </tr>
            }
            <tr>
                <td colspan="5">Tổng thành tiền</td>
                <td class="text-right font-weight-bold text-primary">
                    @{
                        List<ShopDongHo.Models.SanPhamTrongGio> cart = (List<ShopDongHo.Models.SanPhamTrongGio>)Session["cart"];
                        var total = @String.Format("{0:N0}", cart.Sum(item => item.dongho.DonGia * item.soLuongTrongGio)) + " VNĐ";
                    }
                    @total
                </td>
            </tr>
        </table>

        <p>
            <a href="@Url.Action("Index", "GioHang")" class="btn btn-primary">Cập nhật sản phẩm</a>
        </p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShopDongHo/Views/Home/success.cshtml
@{
    ViewBag.Title = "Đăng ký";
}

<p class="alert alert-success"> Đăng ký tài khoản thành công <a class="" href="@Url.Action("Login", "Home")">Đăng nhập</a></p>
    