ShopDongHo/Models/DongHo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDongHo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class DongHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongHo()
        {
            this.DatHang_ChiTiet = new HashSet<DatHang_ChiTiet>();
        }
        [Display(Name = "Mã đồng hồ")]
        public int ID { get; set; }

        [Display(Name = "Thương hiệu")]
        [Required(ErrorMessage = "Chưa chọn thương hiệu!")]
        public Nullable<int> ThuongHieu_ID { get; set; }

        [Display(Name = "Loại đồng hồ")]
        [Required(ErrorMessage = "Chưa chọn loại đồng hồ!")]
        public Nullable<int> TenLoai_ID { get; set; }

        [Display(Name = "Chất liệu đồng hồ")]
        [Required(ErrorMessage = "Chưa chọn Chất liệu đồng hồ!")]
        public Nullable<int> ChatLieu_ID { get; set; }

        [Display(Name = "Xuất xứ")]
        [Required(ErrorMessage = "Chưa chọn xuất xứ đồng hồ!")]
        public Nullable<int> XuatXu_ID { get; set; }

        [Display(Name = "Tên đồng hồ")]
        [Required(ErrorMessage = "Tên đồng hồ không được bỏ trống!")]
        public string TenDongHo { get; set; }

        [Display(Name = "Màu sắc")]
        [Required(ErrorMessage = "Màu sắc không được bỏ trống!")]
        public string MauSac { get; set; }

        [Display(Name = "Hạn bảo hành (tháng)")]
        [Required(ErrorMessage = "Hạn bảo hành không được bỏ trống!")]
        public Nullable<int> HanBaoHanh { get; set; }

        [Display(Name = "Đơn giá")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<int> DonGia { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Hình ảnh đồng hồ")]
        public string HinhAnhDH { get; set; }

        [Display(Name = "Hình ảnh bìa")]
        public HttpPostedFileBase DuLieuHinhAnhDH { get; set; }

        [Display(Name = "Mô tả")]
        [DataType(DataType.MultilineText)]
        public string MoTa { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
        public virtual LoaiDH LoaiDH { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        public virtual XuatXu XuatXu { get; set; }
    }
}

ShopDongHo/Areas/Admin/Controllers/DongHoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopDongHo.Models;

namespace ShopDongHo.Areas.Admin.Controllers
{
    public class DongHoController : AuthController
    {
        private ShopDongHoEntities db = new ShopDongHoEntities();

        // GET: DongHo
        public ActionResult Index()
        {
            var dongHo = db.DongHo.Include(d => d.ChatLieu).Include(d => d.LoaiDH).Include(d => d.ThuongHieu).Include(d => d.XuatXu);
            return View(dongHo.ToList());
        }


        // GET: DongHo/Create
        public ActionResult Create()
        {
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieu, "ID", "TenChatLieu");
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDH, "ID", "TenLoai");
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieu, "ID", "TenThuongHieu");
            ViewBag.XuatXu_ID = new SelectList(db.XuatXu, "ID", "TenQG");
            ModelState.AddModelError("UploadError", "");
            return View();
        }

        // POST: DongHo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "ID,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,DuLieuHinhAnhDH,MoTa")] DongHo dongHo)
        {
           
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieu, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDH, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieu, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXu, "ID", "TenQG", dongHo.XuatXu_ID);
            if (ModelState.IsValid)
            {
                // Upload
                if (!Object.Equals(dongHo.DuLieuHinhAnhDH, null))
                {
                    string folder = "Storage/";
                    string fileName = DateTime.Now.ToFileTime() + "_" + dongHo.DuLieuHinhAnhDH.FileName;
                    string fileExtension = Path.GetExtension(fileName).ToLower();

                    // Kiểm tra kiểu
                    var fileTypeSupported = new[] { ".jpg", ".jpeg", ".png", ".gif" };
                    if (!fileTypeSupported.Contains(fileExtension))
                    {
                        ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin JPG, PNG, GIF!");
                        return View(dongHo);
                    }
                    else if (dongHo.DuLieuHinhAnhDH.ContentLength > 2 * 1024 * 1024)
                    {
                        ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin từ 2MB trở xuống!");
                        return View(dongHo);
                    }
                    else
                    {
                        string filePath = Path.Combine(Server.MapPath("~/" + folder), fileName);
                        dongHo.DuLieuHinhAnhDH.SaveAs(filePath);

                        // Cập nhật đường dẫn vào CSDL
                        dongHo.HinhAnhDH = folder + fileName;

                        db.DongHo.Add(dongHo);
                        db.SaveChanges();
                        SetAlert("Thêm mới thành công", "success");
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError("UploadError", "Hình ảnh bìa không được bỏ trống!");
                    return View(dongHo);
                }
            }


            return View(dongHo);
        }
       
        // GET: Admin/DienThoaiDD/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHo.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieu, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDH, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieu, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXu, "ID", "TenQG", dongHo.XuatXu_ID);
            ModelState.AddModelError("UploadError", "");
            return View(dongHo);
        }

        // POST: Admin/DongHo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ID,HinhAnhDH,ThuongHieu_ID,TenLoai_ID,ChatLieu_ID,XuatXu_ID,TenDongHo,MauSac,HanBaoHanh,DonGia,SoLuong,DuLieuHinhAnhDH,MoTa")] DongHo dongHo)
        {
            
            ViewBag.ChatLieu_ID = new SelectList(db.ChatLieu, "ID", "TenChatLieu", dongHo.ChatLieu_ID);
            ViewBag.TenLoai_ID = new SelectList(db.LoaiDH, "ID", "TenLoai", dongHo.TenLoai_ID);
            ViewBag.ThuongHieu_ID = new SelectList(db.ThuongHieu, "ID", "TenThuongHieu", dongHo.ThuongHieu_ID);
            ViewBag.XuatXu_ID = new SelectList(db.XuatXu, "ID", "TenQG", dongHo.XuatXu_ID);

            if (ModelState.IsValid)
            {
                // upload ảnh mới
                if (!Object.Equals(dongHo.DuLieuHinhAnhDH, null))
                {
                    // Xóa ảnh cũ
                    string oldFilePath = Server.MapPath("~/" + dongHo.HinhAnhDH);
                    if (System.IO.File.Exists(oldFilePath)) System.IO.File.Delete(oldFilePath);

                    string folder = "Storage/";
                    string fileName = DateTime.Now.ToFileTime() + "_" + dongHo.DuLieuHinhAnhDH.FileName;
                    string fileExtension = Path.GetExtension(fileName).ToLower();

                    // Kiểm tra kiểu
                    var fileTypeSupported = new[] { ".jpg", ".jpeg", ".png", ".gif" };
                    if (!fileTypeSupported.Contains(fileExtension))
                    {
                        ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin JPG, PNG, GIF!");
                        return View(dongHo);
                    }
                    else if (dongHo.DuLieuHinhAnhDH.ContentLength > 2 * 1024 * 1024)
                    {
                        ModelState.AddModelError("UploadError", "Chỉ cho phép tập tin từ 2MB trở xuống!");
                        return View(dongHo);
                    }
                    else
                    {
                        string filePath = Path.Combine(Server.MapPath("~/" + folder), fileName);
                        dongHo.DuLieuHinhAnhDH.SaveAs(filePath);

                        // Cập nhật đường dẫn vào CSDL
                        dongHo.HinhAnhDH = folder + fileName;

                        db.Entry(dongHo).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else // Giữ nguyên ảnh cũ
                {
                    db.Entry(dongHo).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(dongHo);
        }

        // GET: DongHo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHo.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: DongHo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DongHo dongHo = db.DongHo.Find(id);
            db.DongHo.Remove(dongHo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopDongHo/Areas/Admin/Views/DongHo/Create.cshtml
@model ShopDongHo.Models.DongHo

@{
    ViewBag.Title = "Thêm đồng hồ";
}



<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm("Create", "DongHo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.ThuongHieu_ID)
                @Html.DropDownList("ThuongHieu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThuongHieu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenLoai_ID)
                @Html.DropDownList("TenLoai_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenLoai_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ChatLieu_ID)
                @Html.DropDownList("ChatLieu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ChatLieu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.XuatXu_ID)
                @Html.DropDownList("XuatXu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.XuatXu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenDongHo)
                @Html.EditorFor(model => model.TenDongHo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MauSac)
                @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HanBaoHanh)
                @Html.EditorFor(model => model.HanBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HanBaoHanh, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonGia)
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLuong)
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DuLieuHinhAnhDH)
                @Html.TextBoxFor(model => model.DuLieuHinhAnhDH, new { @class = "form-control-file", type = "file" })
                @Html.ValidationMessageFor(model => model.DuLieuHinhAnhDH, "", new { @class = "text-danger" })
                @if (!String.IsNullOrEmpty(ViewData.ModelState["UploadError"].Errors[0].ErrorMessage))
                {
                    <span class="d-block text-danger">@ViewData.ModelState["UploadError"].Errors[0].ErrorMessage</span>
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })

                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })

            </div>


            <div class="form-group mb-0">
                <input type="submit" value="Thêm mới" class="btn btn-success" /> hoặc @Html.ActionLink("Quay về danh sách", "Index")
            </div>

        }
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#MoTa'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

ShopDongHo/Areas/Admin/Views/DongHo/Delete.cshtml
@model ShopDongHo.Models.DongHo

@{
    ViewBag.Title = "Xóa đồng hồ";
}

<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Bạn có muốn xóa nhà xuất bản <strong>@Model.TenDongHo</strong> không?
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> hoặc @Html.ActionLink("Quay về danh sách", "Index")
            </div>
        }
    </div>
</div>

ShopDongHo/Areas/Admin/Views/DongHo/Details.cshtml
@model ShopDongHo.Models.DongHo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DongHo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDongHo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDongHo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MauSac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MauSac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HanBaoHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HanBaoHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhDH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhDH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChatLieu.TenChatLieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChatLieu.TenChatLieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDH.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDH.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThuongHieu.TenThuongHieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThuongHieu.TenThuongHieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XuatXu.TenQG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XuatXu.TenQG)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShopDongHo/Areas/Admin/Views/DongHo/Edit.cshtml
@model ShopDongHo.Models.DongHo

@{
    ViewBag.Title = "Cập nhật đồng hồ";
}



<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "DongHo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()      
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.HinhAnhDH)

            <div class="form-group">
                @Html.LabelFor(model => model.ThuongHieu_ID )
                @Html.DropDownList("ThuongHieu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThuongHieu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenLoai_ID )
                @Html.DropDownList("TenLoai_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenLoai_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ChatLieu_ID )
                @Html.DropDownList("ChatLieu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ChatLieu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.XuatXu_ID )
                @Html.DropDownList("XuatXu_ID", null, "-- Chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.XuatXu_ID, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenDongHo )
                @Html.EditorFor(model => model.TenDongHo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MauSac )
                @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HanBaoHanh )
                @Html.EditorFor(model => model.HanBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HanBaoHanh, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DonGia )
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zz, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoLuong )
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DuLieuHinhAnhDH)
                <span class="d-block mb-2"><img src="~/@Model.DuLieuHinhAnhDH" width="80" class="img-thumbnail" /></span>
                <span class="d-block mb-2 mt-2 small text-danger">Bỏ trống nếu không muốn cập nhật ảnh mới!</span>
                @Html.TextBoxFor(model => model.DuLieuHinhAnhDH, new { @class = "form-control-file", type = "file" })
                @Html.ValidationMessageFor(model => model.DuLieuHinhAnhDH, "", new { @class = "text-danger" })
                @if (!String.IsNullOrEmpty(ViewData.ModelState["UploadError"].Errors[0].ErrorMessage))
                {
                    <span class="d-block text-danger">@ViewData.ModelState["UploadError"].Errors[0].ErrorMessage</span>
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MoTa )
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })

            </div>


            <div class="form-group mb-0">
                <input type="submit" value="Cập nhật" class="btn btn-primary" /> hoặc @Html.ActionLink("Quay về danh sách", "Index")
            </div>

        }

    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#MoTa'))
            .catch(error => {
                console.error(error);
            });
    </script>
}